version: '3.8'
services: 
  mongo:
    image: mongo:4.2.5
  frontend:
    build: ./frontend
    environment:
      WAIT_HOSTS: backend:5000
    ports: 
      - '3000:3000'
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '5000:5000'
     